### PR TITLE
Add contributors

### PR DESCRIPTION
**Pull request by felixfong227**
You're welcome

this commit was also made on arch, btw

### CODE REVIEW

**Comment by felixfong227** [comment]
image

i like Sage btw

**Comment by felixfong227** [comment]
And according to my deep learning algorithm, this repo contains no Log4J usage

**Comment by pranay1208** [comment]
Will approve as contributor if you can make the README look nice and informative

**Comment by felixfong227** [comment]
here u go my fd :)

**Comment by pranay1208** [comment]
Can you add some cool badges to it too? Like at the top

**Pull request closed without merging**
